# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
    # Shell is non-interactive.  Be done now!
    return
fi

# be paranoid
if [ $(id -u) != 0 ]; then
    umask 0077
else
    umask 0022
fi

[[ -f $HOME/.bash_theme ]] && . $HOME/.bash_theme

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# do not save empty lines in the history
export HISTCONTROL=ignorespace

# I want a lot..
export HISTFILESIZE=1000

# aliases
if [ -f $HOME/.alias ]; then
    . $HOME/.alias
fi

# create temporary directory for today and clean up old empty ones
if [ $(id -u) -ne 0 ]; then
    OLD_PWD=$(pwd)

    TEMP_ROOT=/tmp
    TEMP_TODAY=$(date +%Y-%m-%d)
    export TEMP_DIR=$TEMP_ROOT/$TEMP_TODAY

    mkdir -p $TEMP_DIR
    cd $TEMP_ROOT
    ls | while read dir; do
        if [ "$dir" != "$TEMP_TODAY" ] && [ "$dir" != "$TEMP_TODAY/" ]; then
            rmdir $dir 2>/dev/null
        fi
    done

    # just type "td" to go to your actual temp directory
    alias td="cd $TEMP_DIR"

    cd $OLD_PWD
fi

# shortcut for making a screenshot
IMPORT="$(which import)"
if [ ! -z $IMPORT ]; then
    alias screenshot="sleep 2 && import -window root -quality 90 $TEMP_DIR/screenshot_$(date +%Y%m%d_%H%M%S).jpg && echo $TEMP_DIR/screenshot_$(date +%Y%m%d_%H%M%S).jpg"
fi

# Put your fun stuff here.
export XMODIFIERS="@im=fcitx"
export XIM=fcitx
export XIM_PROGRAM=fcitx

# load some tools for book algorithms
algs_config="${HOME}/workspace/algorithms/bin/config.sh"
test -r ${algs_config} && source ${algs_config}

export PATH=${PATH}:/opt/FriendlyARM/toolschain/4.5.1/bin
export PATH=${PATH}:$HOME/.vim/local/bin
export PATH=${PATH}:$HOME/Dropbox/bin
