" The file will be only loaded running gvim

if has("win32")
    set langmenu=none
    let $LANG='zh_CN.UTF-8'
    source $VIMRUNTIME/delmenu.vim
    source $VIMRUNTIME/menu.vim
elseif has("unix")
    set guifont=Droid\ Sans\ Mono\ Dotted\ 10,Monospace\ 11
endif
set langmenu=C
set mousemodel=popup        " Enable right click of the mouse.
set columns=94              " The width of the windows
set lines=48
"colorscheme b_gentooish

